
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/fredchan/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/fredchan/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/fredchan/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/fredchan/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

ALIAS="$HOME/code/dotfiles/zsh/alias.sh"
if [ -f "$ALIAS" ]; then
       source $ALIAS
fi

autoload bashcompinit && bashcompinit

PROMPT="%F{008}[%T] %f%F{067}%n:%f%F{137}%c%f %F{172}|%f "

export EDITOR="vim"
export LSCOLORS=ExFxBxDxCxegedabagacad

# enable zsh auto suggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
#bindkey '\t\t' autosuggest-accept

# enable zsh sytax highlight
source $(brew --prefix)/opt/zsh-fast-syntax-highlighting/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# make man page have color using LESS
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'
